-- FERDEL Gestión · Esquema inicial para Supabase/PostgreSQL
-- Ejecutar una vez desde SQL Editor en el panel de Supabase.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null default '',
  role text not null default 'almacen' check (role in ('administrador','almacen','operaciones','gerencia')),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.products (
  id bigint primary key,
  code text not null unique,
  name text not null,
  description text,
  category text not null default '',
  brand text not null default '',
  unit text not null default 'Unidad',
  stock numeric(14,3) not null default 0 check (stock >= 0),
  min_stock numeric(14,3) not null default 0 check (min_stock >= 0),
  max_stock numeric(14,3) not null default 0 check (max_stock >= min_stock),
  purchase_price numeric(14,2) not null default 0 check (purchase_price >= 0),
  location text not null default '',
  supplier_name text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.work_orders (
  id bigint primary key,
  order_number text not null unique,
  client_name text not null,
  plate text not null,
  vehicle text not null default '',
  conversion_type text not null default 'Diésel a GNV',
  admission_date text not null,
  estimated_delivery text not null,
  manager_name text not null default '',
  status text not null default 'Pendiente' check (status in ('Pendiente','En proceso','En espera','Finalizada','Entregada','Cancelada')),
  progress integer not null default 0 check (progress between 0 and 100),
  material_cost numeric(14,2) not null default 0,
  labor_cost numeric(14,2) not null default 0,
  extra_cost numeric(14,2) not null default 0,
  sale_price numeric(14,2) not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.clients (
  id bigint generated by default as identity primary key,
  business_name text not null,
  tax_id text not null unique,
  contact_name text not null default '',
  phone text not null default '',
  associated_units text not null default '',
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.suppliers (
  id bigint generated by default as identity primary key,
  business_name text not null,
  tax_id text not null unique,
  contact_name text not null default '',
  phone text not null default '',
  supplied_products text not null default '',
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.inventory_movements (
  id bigint generated by default as identity primary key,
  movement_number text not null unique,
  movement_type text not null check (movement_type in ('Entrada','Salida')),
  product_id bigint not null references public.products(id),
  work_order_id bigint references public.work_orders(id),
  quantity numeric(14,3) not null check (quantity > 0),
  unit_cost numeric(14,2) not null default 0,
  reference text not null default '',
  notes text not null default '',
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now()
);

create table if not exists public.work_order_expenses (
  id bigint generated by default as identity primary key,
  work_order_id bigint not null references public.work_orders(id) on delete cascade,
  category text not null check (category in ('Mano de obra','Servicio externo','Transporte','Reparación','Consumible','Tercerizado','Otro')),
  description text not null,
  amount numeric(14,2) not null check (amount >= 0),
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now()
);

create table if not exists public.audit_logs (
  id bigint generated always as identity primary key,
  user_id uuid references auth.users(id),
  action text not null,
  entity text not null,
  entity_id text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, full_name)
  values (new.id, coalesce(new.raw_user_meta_data->>'full_name', new.email, ''));
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users
for each row execute procedure public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.products enable row level security;
alter table public.work_orders enable row level security;
alter table public.clients enable row level security;
alter table public.suppliers enable row level security;
alter table public.inventory_movements enable row level security;
alter table public.work_order_expenses enable row level security;
alter table public.audit_logs enable row level security;

drop policy if exists "Usuarios autenticados leen perfiles" on public.profiles;
drop policy if exists "Usuario actualiza su perfil" on public.profiles;
drop policy if exists "Usuarios autenticados gestionan productos" on public.products;
drop policy if exists "Usuarios autenticados gestionan OT" on public.work_orders;
drop policy if exists "Usuarios autenticados gestionan clientes" on public.clients;
drop policy if exists "Usuarios autenticados gestionan proveedores" on public.suppliers;
drop policy if exists "Usuarios autenticados gestionan movimientos" on public.inventory_movements;
drop policy if exists "Usuarios autenticados gestionan gastos" on public.work_order_expenses;
drop policy if exists "Usuarios autenticados leen auditoría" on public.audit_logs;
drop policy if exists "Usuarios autenticados crean auditoría" on public.audit_logs;

create policy "Usuarios autenticados leen perfiles" on public.profiles for select to authenticated using (true);
create policy "Usuario actualiza su perfil" on public.profiles for update to authenticated using (auth.uid() = id) with check (auth.uid() = id);
create policy "Usuarios autenticados gestionan productos" on public.products for all to authenticated using (true) with check (true);
create policy "Usuarios autenticados gestionan OT" on public.work_orders for all to authenticated using (true) with check (true);
create policy "Usuarios autenticados gestionan clientes" on public.clients for all to authenticated using (true) with check (true);
create policy "Usuarios autenticados gestionan proveedores" on public.suppliers for all to authenticated using (true) with check (true);
create policy "Usuarios autenticados gestionan movimientos" on public.inventory_movements for all to authenticated using (true) with check (true);
create policy "Usuarios autenticados gestionan gastos" on public.work_order_expenses for all to authenticated using (true) with check (true);
create policy "Usuarios autenticados leen auditoría" on public.audit_logs for select to authenticated using (true);
create policy "Usuarios autenticados crean auditoría" on public.audit_logs for insert to authenticated with check (auth.uid() = user_id);

grant usage on schema public to authenticated;
grant select, insert, update, delete on public.profiles, public.products, public.work_orders, public.clients, public.suppliers,
  public.inventory_movements, public.work_order_expenses, public.audit_logs to authenticated;
grant usage, select on all sequences in schema public to authenticated;
